name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # - name: Log in to GitHub Container Registry (if needed)
    #   run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    #   if: env.USE_GHCR == 'true'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Create Named Volume
      run: docker volume create vp_data

    - name: Build the Docker image
      run: |
        TIMESTAMP=$(date +%s)
        docker build --file Dockerfile --tag prev-conteneur:$TIMESTAMP .

    - name: Run Docker Container with Named Volume
      run: docker run --rm -v vp_data:/app/vp prev-conteneur train

    - name: Remove Named Volume
      if: always()
      run: docker volume rm vp_data
