name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set environment variables
        run: echo "IMAGE_NAME=prev-conteneur:$(date +%s)" >> $GITHUB_ENV

      - name: Create Named Volume
        run: docker volume create vp_data

      - name: Build the Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Verify Image Exists
        run: docker images | grep prev-conteneur

      - name: Rouler le conteneur en entrainement
        run: docker run --rm -v vp_data:/app/vp $IMAGE_NAME train

      - name: Rouler le conteneur en prévision
        run: docker run --rm -v vp_data:/app/vp $IMAGE_NAME predict

      - name: Remove Named Volume
        if: always()
        run: docker volume rm vp_data
